[package]
name = "qr-gen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
reed-solomon = "0.2.1"
bitstream-io = "1.2.0"
lazy_static = "1.4.0"
itertools = "0.10.1"
